;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ModulesToPreload=SmartFoundations
SourcePath=Mods/GameFeatures/SmartFoundations/Content/Localization/SmartFoundations
DestinationPath=Mods/GameFeatures/SmartFoundations/Content/Localization/SmartFoundations
ManifestName=SmartFoundations.manifest
ArchiveName=SmartFoundations.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
CulturesToGenerate=es
CulturesToGenerate=fr
CulturesToGenerate=it
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=pt-BR
CulturesToGenerate=ru
CulturesToGenerate=tr
CulturesToGenerate=zh-Hans
CulturesToGenerate=zh-Hant
CulturesToGenerate=bg
CulturesToGenerate=hu
CulturesToGenerate=no
CulturesToGenerate=uk
CulturesToGenerate=vi
CulturesToGenerate=ar
CulturesToGenerate=fa
CulturesToGenerate=th

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/SmartFoundations/Source
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/SmartFoundations/Config
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=%LOCPROJECTROOT%Mods/GameFeatures/SmartFoundations/Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/L10N/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ShouldExcludeDerivedClasses=false
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=SmartFoundations.csv
bConflictReport=true
ConflictReportName=SmartFoundations_Conflicts.txt

