; Generated for SmartFoundations localization
[CommonSettings]
SourcePath=Mods/smart/Content/Localization/SmartFoundations
DestinationPath=Mods/smart/Content/Localization/SmartFoundations
ManifestName=SmartFoundations.manifest
ArchiveName=SmartFoundations.archive
ResourceName=SmartFoundations.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
CulturesToGenerate=es
CulturesToGenerate=fr
CulturesToGenerate=it
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=pt-BR
CulturesToGenerate=ru
CulturesToGenerate=tr
CulturesToGenerate=zh-Hans
CulturesToGenerate=zh-Hant
CulturesToGenerate=bg
CulturesToGenerate=hu
CulturesToGenerate=no
CulturesToGenerate=uk
CulturesToGenerate=vi

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

